"""empty message

Revision ID: 06af2d00ed92
Revises: 
Create Date: 2019-04-21 01:40:09.557970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06af2d00ed92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages_data', sa.Column('settings_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages_data', 'settings', ['settings_id'], ['id'])
    op.drop_column('settings', 'nick')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('settings', sa.Column('nick', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'messages_data', type_='foreignkey')
    op.drop_column('messages_data', 'settings_id')
    # ### end Alembic commands ###
